MyVideoFragment
nbc-3-6/DopamineMoa pull request #18
Opened 2024-05-21 08:08 UTC by theBettor

- [x]  뒤로가기 버튼
    - [ ]  뒤로가기가 안됨
- [x]  iv_profie, tv_name,  tv_description
    - [ ]  우측 상단에 수정 버튼 하나 만들어서 dialogfragemnt로 프로필 정보 수정하게 하면 좋을 것 같다.
- [x]  divider
- [x]  tv_list_name
- [x]  recyclerview
    - [x]  item_rv

- 보완해야할 점
1. 좋아요를 취소하고 다시 누르면 위에서 부터 쌓이는게 아니라 바닥에서부터 쌓이는것 같다, 위에서부터 쌓이게 하는 방법을 찾아서 수정할 예정
2. Figma대로 레이아웃을 marginTop 71정도 넣어줬었는데 에뮬레이터에서보는건 너무 별로라 피그마가 보완이 되어야하는 부분인가 싶다.
3. ViewModel, Adapter, Fragment 중에 Fragment만 코드 확신이 없어서 캡슐화가 필요해보이는 코드들이 있는데 나중에 꼭 수정하겠습니다!

2024-05-21 08:28 UTC, BanDalKang commented on app/src/main/java/com/example/dopaminemoa/presentation/myvideo/MyVideoViewModel.kt
> +            _likedItems.value = videoRepository.getStorageItems()
레포지토리에 만들어둔 함수 사용이 잘 되어서 다행이네요
고생 많으셨습니다.

2024-05-21 08:28 UTC, BanDalKang approved these changes

2024-05-21 08:59 UTC, neoneoneo123 requested changes
고생 많으셨습니다!
my video가 종착지 같은 곳이라 PR을 보니 프로젝트가 끝나가는 것 같아 홀가분한 기분이 드네요..!

약간에 수정이 더 해진다면 좋을 것 같아 코멘트를 몇 개 남겼습니다.
확인 부탁드립니다!

2024-05-21 08:59 UTC, neoneoneo123 commented on app/src/main/res/layout/myvideo_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
음.. figma를 보시면 my video fragment와 search fragment에서 사용하는 item의 디자인이 같습니다.

별도로 item을 위한 xml을 만들어서 사용하시는 것 보다는 기존에 만들어져 있는 리소스(search_item.xml)를 사용해보는 건 어떠신가요?

![image](https://github.com/nbc-3-6/DopamineMoa/assets/128209823/5b032ce8-3dbf-4b2d-9a1c-aab697474edf)

2024-05-21 08:59 UTC, neoneoneo123 commented on app/src/main/java/com/example/dopaminemoa/presentation/myvideo/MyVideoAdapter.kt
> +        Log.d("updateList", items.toString())
log 창에 길게 남을 수 있는 log는 지우는 게 좋을 것 같습니다!

2024-05-21 08:59 UTC, neoneoneo123 commented on app/src/main/java/com/example/dopaminemoa/presentation/myvideo/MyVideoFragment.kt
>  class MyVideoFragment : Fragment() {
home 탭에서 새로운 아이템에 좋아요를 누르거나,
detail로 넘어가서 좋아요를 해지했을 때 my video tab의 리스트가 갱신되는 게 좋을 것 같습니다.

2024-05-21 08:59 UTC, neoneoneo123 commented on app/src/main/res/layout/fragment_my_video.xml
> +            />
생각해보니 my video에서 back 버튼은 필요 없겠네요.
이 부분은 지우셔도 괜찮을 것 같습니다!

2024-05-21 15:55 UTC, theBettor commented on app/src/main/res/layout/myvideo_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
오 이건 시도 해보겠습니다.

2024-05-21 15:56 UTC, theBettor commented on app/src/main/java/com/example/dopaminemoa/presentation/myvideo/MyVideoAdapter.kt
> +        Log.d("updateList", items.toString())
수정 완료 했습니다 감사합니다!

2024-05-21 15:57 UTC, theBettor commented on app/src/main/res/layout/fragment_my_video.xml
> +            />
수정 완료 했습니다 감사합니다!

2024-05-21 15:58 UTC, theBettor commented on app/src/main/java/com/example/dopaminemoa/presentation/myvideo/MyVideoFragment.kt
>  class MyVideoFragment : Fragment() {
오 이건 잘 모르겠어서 따로 찾아뵙고 여쭙겠습니다

2024-05-22 09:24 UTC, neoneoneo123 approved these changes

2024-05-22 09:26 UTC, merged