Home 완성
nbc-3-6/DopamineMoa pull request #9
Opened 2024-05-17 06:05 UTC by Combro-Kim

- [x]  **홈 화면 (HomeFragment)**
    - 사용자에게 YouTube의 현재 인기 및 새로운 콘텐츠를 중점적으로 보여주는 핵심 화면
    - [x]  **Most Popular Videos, Category Videos, Category Channels** 목록을 스크롤이 가능한 RecyclerView 형태로 나열하여 출력하세요.
    - [x]  **Most Popular Videos 목록 구현**
        - [x]  YouTube의 현재 Trend 비디오 목록을 출력하세요.
        - [x]  **API 활용**: **`videos`** 엔드 포인트에 **`chart=mostPopular`** 파라미터를 사용하여 최신 인기 비디오 목록을 획득하세요.
    - [x]  **Category Videos 목록**
        1. **비디오 카테고리 조회**
            - [x]  YouTube에서 제공하는 다양한 비디오 카테고리를 조회해보세요.
            - [x]  **API 연동**: **`videoCategories`** 엔드 포인트를 사용하여 원하는 국가의 비디오 카테고리 목록을 가져와 참조하세요.
        2. **카테고리 별 비디오 목록 조회**
            - [x]  특정 카테고리에 속하는 인기 비디오 목록을 조회하세요.
            - [x]  **API 연동**: **`videos`** 엔드 포인트에 **`videoCategoryId`** 파라미터를 활용하여 해당 카테고리의 가장 인기 있는(**`chart=mostPopular`)** 비디오 목록을 가져오세요.
    - [x]  **Category Channels 목록**
        - [x]  특정 카테고리에 속하는 비디오의 각 채널들의 정보를 조회해 보세요.
        - [x]  **API 연동**: **`channels`** 엔드 포인트를 활용하고, **`id`** 파라미터에 채널 ID 값을 넣어 해당 채널의 정보를 가져오세요.
        - [x]  가져온 채널 정보 중  **`snippet`** 부분을 활용하여, 채널의 기본 정보와 대표 이미지를 정확히 표시하십시오. API를 사용할 때 **`part`** 파라미터에 **`snippet`** 값을 넣어 주어야 해요.

2024-05-17 06:19 UTC, BanDalKang approved these changes
딱히 문제있는 부분은 없어보입니다. 
고생 많으셨습니다.

2024-05-17 07:15 UTC, neoneoneo123 requested changes
여러 api를 처리해야 하는 화면이라 많은 코드를 작성하셔야 했던 것 같습니다.
화면 구현을 비롯하여 api 연동에 필요한 data class 생성에 고생 많으셨습니다.

재혁님의 코드를 보면서 제 코드도 함께 살펴보니, VideoViewModel을 하나로 통합하여 사용하는 부분에 대한 이점이 과연 있을까? 하는 고민이 들었습니다. 일단 두 기능을 합쳐놨을 때에는 home, search 간에 "공유"가 필요한 데이터는 없을 것 같아서요. 다만,, detail 화면으로 보내서 좋아요를 누르고 my page에서 확인할 수 있도록 하는 부분이 필요하기 때문에.. 모든 화면이 같은 viewmodel을 써야하는 건가? 고민이 되네요.

앞으로 합쳐질 현정님, 찬교님 코드를 함께 살펴보면서 더 고민해보고 말씀드리겠습니다!

2024-05-17 07:15 UTC, neoneoneo123 commented on app/src/main/res/layout/fragment_home.xml
저희가 스크롤바에 디자인을 입히지는 않을 것 같은데,     android:scrollbars="none" 를 추가해서 default 스크롤바를 없애는 건 어떨까요?

2024-05-17 07:15 UTC, neoneoneo123 commented on app/src/main/res/layout/item_video_list.xml
> +            android:scaleType="fitXY"
fitXY로 설정해두면 이미지 비율이 깨지는 것 같습니다. 대신에 center 또는 centerCrop으로 변경해보는 건 어떨까요?


![스크린샷 2024-05-17 오후 3 40 12](https://github.com/nbc-3-6/DopamineMoa/assets/128209823/e428b0ea-02b3-4fe2-8a55-a4d6489c44aa)
![스크린샷 2024-05-17 오후 3 39 58](https://github.com/nbc-3-6/DopamineMoa/assets/128209823/ff7cd831-0023-4dfc-b557-ac4eba6e475c)

2024-05-17 07:15 UTC, neoneoneo123 commented on app/src/main/java/com/example/dopaminemoa/presentation/home/HomeFragment.kt
> +                TODO("Not yet implemented")
사용하지 않는 override 함수의 Todo는 제거하고
// No action needed 와 같은 주석을 두는 건 어떨까요?

2024-05-17 07:15 UTC, neoneoneo123 commented on app/src/main/java/com/example/dopaminemoa/repository/VideoRepository.kt
>      }
api 통신 에러 발생 시 예외 처리가 필요할 것 같습니다~

2024-05-17 07:37 UTC, Combro-Kim commented on app/src/main/res/layout/fragment_home.xml
단순히 ConstraintLayout를 ScrollView로 바꿔서 신경 쓰지 않았었네요. 피드백 감사합니다.

2024-05-17 08:06 UTC, Combro-Kim commented on app/src/main/res/layout/item_video_list.xml
> +            android:scaleType="fitXY"
말씀하신 깨지는 이미지는 shorts thumbnail입니다. 가로 길이가 은근 길더라고요..
center와 centerCrop을 사용할 경우에는 shorts의 영상이 아닌 경우는 짤리게 됩니다. 
<img src="https://github.com/nbc-3-6/DopamineMoa/assets/84631435/75f70ca5-7200-444f-b680-af58e98d607a" height="500" width="230">|<img src="https://github.com/nbc-3-6/DopamineMoa/assets/84631435/60609a0a-9597-4816-a608-25a1c626554c" height="500" width="230">
--- | --- |
저희는 shorts만 가져오는 걸 사용할거여서 shorts를 가져오는 부분을 구현하면 그때 수정할까 합니다!!
피드백 감사합니다

2024-05-17 08:09 UTC, Combro-Kim commented on app/src/main/res/layout/item_video_list.xml
> +            android:scaleType="fitXY"
피드백 감사합니다.
![image](https://github.com/nbc-3-6/DopamineMoa/assets/84631435/c4af851d-9402-47c4-8a33-408d6311ff2d)

말씀하신 깨지는 이미지는 shorts thumbnail입니다. 가로 길이가 은근 길더라고요..
center와 centerCrop을 사용할 경우에는 shorts의 영상이 아닌 경우는 짤리게 됩니다.
![image](https://github.com/nbc-3-6/DopamineMoa/assets/84631435/c1c778f8-7617-420c-9cef-d5ddb08c6fd5)
(올려주신 왼쪽 상단부분의 이미지입니다.)
저희는 shorts만 가져오는 걸 사용할 거여서 shorts를 가져오는 부분을 구현하면 더 디테일하게 신경쓰려합니다!!

2024-05-17 08:17 UTC, Combro-Kim commented on app/src/main/java/com/example/dopaminemoa/presentation/home/HomeFragment.kt
> +                TODO("Not yet implemented")
수정했습니다. 감사합니다!

2024-05-20 06:08 UTC, neoneoneo123 approved these changes

2024-05-20 06:09 UTC, BanDalKang approved these changes

2024-05-20 06:12 UTC, merged